title: Pablo Melchi Blog
description: > # this means to ignore newlines until "baseurl:"
  Technical blog about some challenges and findings that I migh find useful in the future.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.pablomelchi.com/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "https://twitter.com/pmelchi" #if your site has a twitter account, enter it here

# Author Settings
author: Pablo Melchi # add your name
author-img: pablo-melchi.jpg # add your photo
about-author: >
  Hello, I'm Pablo! With over 20 years in technology, this blog is my chronicle of intriguing discoveries and innovative solutions encountered along my professional journey as a Solution Architect, Software Developer and Cybersecurity.
social-twitter: pmelchi #add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: pmelchi # add your Github handle
social-linkedin: pablomelchi # add your Linkedin handle
#social-email: # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
# Google Analytics
analytics: UA-162209898-1

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
